SELECT  TOP 26500
*
FROM    
                (SELECT A.[ENCRYPTED_ID], A.[FIRST_NAME], A.[LAST_NAME], A.[EMAIL_ADDRESS], A.[UAC], A.[COUNTRY]
                , ROW_NUMBER() OVER (PARTITION BY A.[EMAIL_ADDRESS] ORDER BY A.[EMAIL_ADDRESS]) as rn 
FROM Ent.[SOURCE_DATA_EXTENSION] A 
INNER JOIN [PHARMABRAND_LAUNCHDATE_DATA] B ON A.[EMAIL_ADDRESS] = B.[EMAIL_ADDRESS]
INNER JOIN ENT._subscribers s ON B.[EMAIL_ADDRESS] =  s.[SubscriberKey]
WHERE 

    A.[EMAIL_ADDRESS] NOT LIKE  
    '%@POL.NET'
    AND A.[EMAIL_ADDRESS] NOT LIKE  
    '%@WORLDNET.ATT.NET'

AND (s.Status = 'active' OR s.Status = 'bounced')

AND

 A.[EMAIL_ADDRESS] NOT IN  
    (SELECT [EMAIL_ADDRESS]  
     FROM [A_OPTOUT_DATA_EXTENSION]  
    )

AND

A.[EMAIL_ADDRESS] NOT IN  
    (SELECT [EMAIL_ADDRESS]  
     FROM [GLOBAL_OPTOUT_DATA_EXTENSION]  
    )

AND

A.[EMAIL_ADDRESS] NOT IN  
    (SELECT [EMAIL_ADDRESS]  
     FROM [NOPROMO_OPTOUT_DATA_EXTENSION]  
    )



) as t 
                
WHERE   t.rn = 1 
  ORDER BY NEWID()